### ISSUE TITLE
Getting one month

### ISSUE THREAD

**Issue by fligen** [jvasallo/jquery-mortgage#1]
is there a way to get the data from one month out of the amortization schedual ie the 84th months data.

**Comment by jvasallo** [comment]
The data is there, it should be able to be pulled apart. How are you suggesting it be displayed? Optional month block?

See how it looks today here:
http://joelvasallo.com/mortgage.html

**Comment by fligen** [comment]
What I’m trying to get is the 84th month data on a 30 year note. IE the total interest paid that months payments and so on, basically the 84th row out of the amortization chart.

**Comment by jvasallo** [comment]
It should be easy enough to show, but we would need to prompt the user: "enter specific month" or something?

Not sure how you want to propose the User to interact with it.

**Comment by fligen** [comment]
No, i need to specify on the back end. and it will be the 84th month

trying to do a 7 year cost assessment vs rent.

**Comment by jvasallo** [comment]
If needed, feel free to fork, but the fix should be easy enough to do! 👍  Like I mentioned, the data is there, you just need to parse it out using jQuery.
